### PR TITLE
Make gunstage also work as `git unstage`

### PR DESCRIPTION
**Pull request by unixorn**
### Description

* Update so that `gunstage` is a fully integrated `git unstage` command too.
* Keep backward compatibility with old cli usage too

### Motivation and context

* Make `gunstage` consistent with other `git` commands
* Make it findable with tab completion
* Maintain backward-compatibility for existing users.

### How this pull was tested

This only changes the packaging, not the `gunstage` code.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by LucasLarson** [comment]
I might be a few days before I merge, but this looks spectacular. Thank you, @unixorn!

**Comment by unixorn** [comment]
Glad to help. Once it's merged, I'll add a link to it from https://github.com/unixorn/git-extra-commands

**Comment by LucasLarson** [comment]
> Keep backward compatibility with old cli usage too
> Maintain backward-compatibility for existing users.

One breaking change I found during testing is filenames with spaces in them no longer mirror vanilla Git’s behavior. The wrong files are now unstaged if you perform the following sequence:
```shell
git init && touch a a\ b b # create three files: “a”, “a b”, and “b”
git add . # stage the new files
git unstage a\ b # try to unstage only “a b”, but “a b” is the only file that remains staged
```

**Comment by unixorn** [comment]
Does it work if you change `gunstage "$@"` to `gunstage $@`?

**Comment by unixorn** [comment]
I was able to get it to work properly on files with spaces in their names by switching `gunstage "$@"` to `gunstage $@` in `git-unstage`. Shellcheck complains but since it works and the `shellcheck` recommendation didn't...

**Review by LucasLarson — APPROVED** [review]
> [Shellcheck complains](https://github.com/LucasLarson/gunstage/pull/32#issuecomment-726190692)

This was my concern, too, especially since the expansion of `git` commands is new to me – my fingers are crossed 🤞

**Pull request merged**
